version: '3.5'

services:
    app:
        build: .
        container_name: url_shortener
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
            - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - 8000:80